export const ships = [
    {
        name: "Allure Of The Seas",
        lat: 26.16885,
        lon: -78.7939,
        speed: 10.8,
        dest: "PEF US",
        minutesAgo: 14,
        cruiseLine: "Royal Caribbean",
    },
    {
        name: "Star Of The Seas",
        lat: 26.8674,
        lon: -79.73662,
        speed: 22.2,
        dest: "Port Canaveral",
        minutesAgo: 1,
        cruiseLine: "Royal Caribbean",
    },
    {
        name: "Icon Of The Seas",
        lat: 24.58229,
        lon: -80.80918,
        speed: 19.1,
        dest: "Costa Maya",
        minutesAgo: 31,
        cruiseLine: "Royal Caribbean",
    },
    {
        name: "Utopia Of The Seas",
        lat: 25.7313,
        lon: -76.16271,
        speed: 12.6,
        dest: "BSPCC",
        minutesAgo: 11,
        cruiseLine: "Royal Caribbean",
    },
    {
        name: "Wonder Of The Seas",
        lat: 25.70245,
        lon: -77.4131,
        speed: null,
        dest: "Nassau",
        minutesAgo: 3,
        cruiseLine: "Royal Caribbean",
    },
    {
        name: "Spectrum Of The Seas",
        lat: 32.66638,
        lon: 126.15538,
        speed: 14.8,
        dest: "Hakata-Fukuoka City",
        minutesAgo: 6,
        cruiseLine: "Royal Caribbean",
    },
    {
        name: "Odyssey Of The Seas",
        lat: 39.15244,
        lon: -73.38715,
        speed: 17.3,
        dest: "New York",
        minutesAgo: 55,
        cruiseLine: "Royal Caribbean",
    }
];
